### ISSUE TITLE
Not identical as demo

### ISSUE THREAD

**Issue by oijkn** [Insolita/InteractiveJobs#1]
Hello,

First of all thanks for the sharing, I integrated your project after installing Laravel "5.6.*". Then I used the command `composer install`.

- The database MySQL contains all the necessary tables.
- The `.env` file and `config/database.php` are well configured.
- Rights on folders are well applied as well.
- Run command `php artisan config:clear`

I noticed a huge slowness when I load the route `home` for example. After some investigation, I found that if I comment the `socket.io` line in `resources/views/layouts/app.blade.php` I no longer have a problem with slowness. However, I no longer have the function of the socket.io

If I compare your demo GIFs I don't have the same functions on my machine.
Flash messages or job list details (via the blue button) do not seem to work...

**Without socket.io**
![jobs](https://user-images.githubusercontent.com/18188407/67100016-3dd61a80-f1bf-11e9-8211-c53e1baa5455.gif)

**With socket.io**
![socket](https://user-images.githubusercontent.com/18188407/67100098-5a725280-f1bf-11e9-9941-8c0c08190686.gif)

Thank you in advance for your reply and support.

BR.

**Comment by Insolita** [comment]
HI, have you installed laravel echo server https://github.com/tlaverdure/laravel-echo-server ?
You also shoud run "npm install && npm run dev" (or "yarn") 
This repo is shared example for my articles
https://medium.com/@DonnaInsolita/organize-realtime-job-management-with-laravel-and-vue-step-by-step-part-1-211fcb4a8f84

And also i wrote it more than year ago, so maybe something has been changed with laravel-echo version.

**Comment by oijkn** [comment]
@Insolita Thank you for your reply, I will test to add laravel echo server and tell you if it's better :)

Edit : Thank you ! All works like a charm :)
